[package]
name = "make_c_version_header"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"

[profile.dev]
opt-level = 3               # 使用稍高一些的优化级别，最低是0，最高是3
overflow-checks = false     # 关闭整数溢出检查
